# ABOUTME: Copies each skill's slice of src/references and src/scripts into metacognition/skills/<skill>/.
# ABOUTME: --check reports missing, extra, and differing files without writing anything.
"""Sync the shared references and scripts from src/ into each skill directory.

src/ is the single source of truth. The copies under
metacognition/skills/<skill>/references/ and .../scripts/ are generated by this
tool and never edited by hand.

A normal run makes each skill's references/ and scripts/ hold exactly its
manifest slice, byte-identical to src/. Anything else inside those two
directories is removed. Nothing outside them is touched: a skill's SKILL.md and
every other file stay as they are.

The tool refuses to run through a symlink. If a skill directory, or its
references/ or scripts/ directory, is a symlink, the paths it would delete from
and write to lie outside the skills tree, so the run fails with exit 2 naming the
path. Every such path is checked up front, before any write, in both modes, so a
refusal never leaves a partial sync.

Inside a real references/ or scripts/ directory a symlink is an entry that does
not belong there, whatever its name and whatever it points at. A normal run
unlinks the link itself (never following it) and, if its name is in the slice,
writes a fresh regular file in its place. ``--check`` never reads through a link:
a link at a slice name is reported as ``differing`` (even when its target holds
identical bytes), any other link is reported as ``extra``, and a link to a
directory is reported as one entry without listing what is inside it.

Interpreter caches and OS litter (``__pycache__``, ``*.pyc``, ``.DS_Store``) show
up inside a skill's scripts/ directory when someone runs a script there. They are
gitignored and are not sync content. They are never copied, a normal run removes
them, and ``--check`` does not report them as extra (reporting them would fail the
drift guard on a developer's machine after running a script).

Usage:
    python tools/sync_skills.py            # sync
    python tools/sync_skills.py --check    # report drift, write nothing, exit 1 on drift

A manifest entry whose source file is missing, or a symlinked target directory,
is an error in both modes (exit 2, message on stderr).
"""

import argparse
import shutil
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT / "src"
DEFAULT_SKILLS = REPO_ROOT / "metacognition" / "skills"

# The manifest is the single hand-maintained source of which shared files each
# skill ships. It must track the table under spec.md goal G2; the test in
# tests/test_sync_manifest.py holds the same table and fails on any departure.
# Keys under each skill are the subdirectory names, values are file names in src/<kind>/.
MANIFEST: Mapping[str, Mapping[str, tuple[str, ...]]] = {
    "design": {
        "references": ("settings.md", "extraction-theory.md", "interview-spec-format.md", "research-contract.md"),
        "scripts": ("yaml_subset.py", "resolve_config.py"),
    },
    "interview": {
        "references": ("settings.md", "extraction-theory.md", "interview-spec-format.md", "archive-format.md"),
        "scripts": ("yaml_subset.py", "resolve_config.py", "validate_artifacts.py"),
    },
    "compile": {
        "references": (
            "settings.md",
            "extraction-theory.md",
            "interview-spec-format.md",
            "archive-format.md",
            "profile-format.md",
        ),
        "scripts": ("yaml_subset.py", "resolve_config.py", "validate_artifacts.py"),
    },
    "calibrate": {
        "references": (
            "settings.md",
            "extraction-theory.md",
            "interview-spec-format.md",
            "profile-format.md",
            "calibration-protocol.md",
        ),
        "scripts": ("yaml_subset.py", "resolve_config.py", "validate_artifacts.py"),
    },
    "skillify": {
        "references": (
            "settings.md",
            "extraction-theory.md",
            "interview-spec-format.md",
            "archive-format.md",
            "profile-format.md",
            "skill-scaffold.md",
        ),
        "scripts": ("yaml_subset.py", "resolve_config.py"),
    },
}

LITTER_DIRS = frozenset({"__pycache__"})
LITTER_NAMES = frozenset({".DS_Store"})
LITTER_SUFFIXES = frozenset({".pyc"})


class SourceMissingError(FileNotFoundError):
    """A file named by the manifest does not exist under src/."""


class SymlinkTargetError(OSError):
    """A skill directory, or its references/ or scripts/ directory, is a symlink."""


@dataclass(frozen=True)
class Drift:
    """One difference between src/ and a skill's copy."""

    kind: str  # "missing", "extra", or "differing"
    path: str  # relative to the skills root, with forward slashes

    def __str__(self) -> str:
        return f"{self.kind}: {self.path}"


def is_litter(path: Path) -> bool:
    """Return True for interpreter caches and OS litter, which are not sync content."""
    return bool(LITTER_DIRS.intersection(path.parts)) or path.name in LITTER_NAMES or path.suffix in LITTER_SUFFIXES


def verify_sources(src_root: Path, manifest: Mapping[str, Mapping[str, tuple[str, ...]]] = MANIFEST) -> None:
    """Raise SourceMissingError naming every manifest file absent from src_root."""
    missing = sorted(
        {
            f"{kind}/{name}"
            for slice_ in manifest.values()
            for kind, names in slice_.items()
            for name in names
            if not (src_root / kind / name).is_file()
        }
    )
    if missing:
        raise SourceMissingError(f"manifest names files missing from {src_root}: {', '.join(missing)}")


def verify_targets(skills_root: Path, manifest: Mapping[str, Mapping[str, tuple[str, ...]]] = MANIFEST) -> None:
    """Raise SymlinkTargetError naming every skill, references/, or scripts/ path that is a symlink."""
    linked = sorted(
        str(path)
        for skill, slice_ in manifest.items()
        for path in (skills_root / skill, *(skills_root / skill / kind for kind in slice_))
        if path.is_symlink()
    )
    if linked:
        raise SymlinkTargetError(f"refusing to sync through symlinked directories: {', '.join(linked)}")


def extra_entries(directory: Path) -> list[Path]:
    """List every entry under directory that is a file or a symlink, never descending through a symlink.

    Symlinks are returned as entries and not followed, so a link to a directory
    contributes itself and nothing from inside the target. Real subdirectories
    are walked. Litter is filtered by the caller, and only for non-symlinks.
    """
    found: list[Path] = []
    for entry in sorted(directory.iterdir()):
        if entry.is_symlink() or not entry.is_dir():
            found.append(entry)
        else:
            found.extend(extra_entries(entry))
    return found


def diff_directory(source_dir: Path, target_dir: Path, names: tuple[str, ...], label: str) -> list[Drift]:
    """Compare one skill subdirectory against its slice. Reads only, and never through a symlink.

    A slice name that exists as a symlink is reported as "differing": a link is
    not a generated copy, whatever it points at, and its target is never read.
    """
    drift: list[Drift] = []
    for name in names:
        target = target_dir / name
        if target.is_symlink():
            drift.append(Drift("differing", f"{label}/{name}"))
        elif not target.is_file():
            drift.append(Drift("missing", f"{label}/{name}"))
        elif target.read_bytes() != (source_dir / name).read_bytes():
            drift.append(Drift("differing", f"{label}/{name}"))
    if target_dir.is_dir():
        for path in extra_entries(target_dir):
            relative = path.relative_to(target_dir)
            if path.is_symlink():
                if relative.parent == Path(".") and path.name in names:
                    continue  # already reported as differing
            elif relative.as_posix() in names or is_litter(relative):
                continue
            drift.append(Drift("extra", f"{label}/{relative.as_posix()}"))
    return drift


def sync_directory(source_dir: Path, target_dir: Path, names: tuple[str, ...]) -> None:
    """Make target_dir hold exactly names, copied byte for byte from source_dir.

    Symlinks are never kept and never followed: a link is unlinked as an entry,
    and rmtree runs only on real directories. After the cleanup pass no slice
    path is a symlink, so the writes below cannot land outside target_dir.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    for entry in target_dir.iterdir():
        if entry.name in names and entry.is_file() and not entry.is_symlink():
            continue
        if entry.is_dir() and not entry.is_symlink():
            shutil.rmtree(entry)
        else:
            entry.unlink()
    for name in names:
        (target_dir / name).write_bytes((source_dir / name).read_bytes())


def find_drift(
    src_root: Path, skills_root: Path, manifest: Mapping[str, Mapping[str, tuple[str, ...]]] = MANIFEST
) -> list[Drift]:
    """Return every missing, extra, and differing file. Writes nothing."""
    verify_sources(src_root, manifest)
    verify_targets(skills_root, manifest)
    drift: list[Drift] = []
    for skill, slice_ in manifest.items():
        for kind, names in slice_.items():
            drift.extend(diff_directory(src_root / kind, skills_root / skill / kind, names, f"{skill}/{kind}"))
    return drift


def sync(src_root: Path, skills_root: Path, manifest: Mapping[str, Mapping[str, tuple[str, ...]]] = MANIFEST) -> None:
    """Write each skill's slice. Validates every source and target before changing anything."""
    verify_sources(src_root, manifest)
    verify_targets(skills_root, manifest)
    for skill, slice_ in manifest.items():
        for kind, names in slice_.items():
            sync_directory(src_root / kind, skills_root / skill / kind, names)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the tool. Returns 0 clean, 1 on drift in --check mode, 2 on a missing source or a symlinked target."""
    parser = argparse.ArgumentParser(description="Sync shared references and scripts from src/ into each skill.")
    parser.add_argument("--check", action="store_true", help="report drift and write nothing; exit 1 if any")
    parser.add_argument("--src", type=Path, default=DEFAULT_SRC, help="source root (default: repo src/)")
    parser.add_argument(
        "--skills", type=Path, default=DEFAULT_SKILLS, help="skills root (default: repo metacognition/skills/)"
    )
    args = parser.parse_args(argv)
    try:
        if args.check:
            drift = find_drift(args.src, args.skills)
            for item in drift:
                print(item)
            return 1 if drift else 0
        sync(args.src, args.skills)
    except (SourceMissingError, SymlinkTargetError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
